- hosts: localhost
  connection: local
  gather_facts: True

- name: Include a play for MacOS
  import_playbook: mac.yaml
  when:
    - ansible_distribution == "MacOSX"

- name: Include a play for Fedora
  import_playbook: fedora.yaml
  when:
    - ansible_distribution == "Fedora"
