- hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - debug: msg="hello world"

- name: Include a play for MacOS
  import_playbook: macos.yaml
  when:
    - ansible_distribution == "MacOSX"

- name: Include a play for Fedora
  import_playbook: fedora.yaml
  when:
    - ansible_distribution == "Fedora"
