- hosts: localhost
  connection: local
  tasks:
  - name: homebrew update
    homebrew:
      update_homebrew: yes

  - name: install homebrew packages
    homebrew:
      name: ['zplug', 'fzf', 'neovim', 'cmake']
      state: latest

  - name: install pip3 packages
    pip:
      name: ['neovim']
      state: latest
      executable: pip3

  - name: install vim-plug for neovim
    command:
      cmd: curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      warn: false
